# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PointCloud.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PointCloud.proto',
  package='pointcloud',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10PointCloud.proto\x12\npointcloud\"\x0e\n\x0cPointRequest\"4\n\nPointReply\x12\x13\n\x0bndarray_pcd\x18\x01 \x03(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\t2U\n\nMainServer\x12G\n\x0fget_point_cloud\x12\x18.pointcloud.PointRequest\x1a\x16.pointcloud.PointReply\"\x00\x30\x01\x62\x06proto3'
)




_POINTREQUEST = _descriptor.Descriptor(
  name='PointRequest',
  full_name='pointcloud.PointRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=46,
)


_POINTREPLY = _descriptor.Descriptor(
  name='PointReply',
  full_name='pointcloud.PointReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ndarray_pcd', full_name='pointcloud.PointReply.ndarray_pcd', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='pointcloud.PointReply.timestamp', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['PointRequest'] = _POINTREQUEST
DESCRIPTOR.message_types_by_name['PointReply'] = _POINTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PointRequest = _reflection.GeneratedProtocolMessageType('PointRequest', (_message.Message,), {
  'DESCRIPTOR' : _POINTREQUEST,
  '__module__' : 'PointCloud_pb2'
  # @@protoc_insertion_point(class_scope:pointcloud.PointRequest)
  })
_sym_db.RegisterMessage(PointRequest)

PointReply = _reflection.GeneratedProtocolMessageType('PointReply', (_message.Message,), {
  'DESCRIPTOR' : _POINTREPLY,
  '__module__' : 'PointCloud_pb2'
  # @@protoc_insertion_point(class_scope:pointcloud.PointReply)
  })
_sym_db.RegisterMessage(PointReply)



_MAINSERVER = _descriptor.ServiceDescriptor(
  name='MainServer',
  full_name='pointcloud.MainServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=102,
  serialized_end=187,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_point_cloud',
    full_name='pointcloud.MainServer.get_point_cloud',
    index=0,
    containing_service=None,
    input_type=_POINTREQUEST,
    output_type=_POINTREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MAINSERVER)

DESCRIPTOR.services_by_name['MainServer'] = _MAINSERVER

# @@protoc_insertion_point(module_scope)
